In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import mysql.connector

db = mysql.connector.connect(
    host="localhost",
    user="root",
    password="secret",
    port="3306",
    database="serlo",
    charset="latin1"
)

pd.set_option('display.max_rows', None)

/home/kulla/.local/share/asdf/installs/python/3.9.1/lib/python3.9/site-packages/pandas/compat/__init__.py:97: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)

In [5]:
pd.read_sql("""
    select type.name, instance.subdomain, count(entity.id) from entity
    join uuid on uuid.id = entity.id
    join type on type.id = entity.type_id
    join instance on entity.instance_id = instance.id
    where uuid.trashed = 0
    group by entity.type_id, instance.subdomain
    order by instance.subdomain
""", db)

                                       name subdomain  count(entity.id)
0                                    course        de               575
1                       text-exercise-group        de              2607
2                single-choice-right-answer        de               530
3              multiple-choice-wrong-answer        de               567
4                               course-page        de              3431
5                     grouped-text-exercise        de              9549
6                single-choice-wrong-answer        de              1044
7                             text-solution        de             11788
8        input-number-exact-match-challenge        de               517
9                                     event        de                23
10                                   applet        de               143
11                            text-exercise        de              4012
12  input-string-normalized-match-challenge        de               127
13                                    video        de               433
14   input-expression-equal-match-challenge        de               148
15                                  article        de              2915
16                              math-puzzle        de                68
17             multiple-choice-right-answer        de               468
18       input-number-exact-match-challenge        en                 1
19                                   applet        en                19
20                                   course        en                39
21               single-choice-right-answer        en                 1
22                            text-solution        en               641
23                              math-puzzle        en                 2
24                                  article        en               262
25               single-choice-wrong-answer        en                 3
26                              course-page        en               181
27                            text-exercise        en               139
28  input-string-normalized-match-challenge        en                 1
29                                    video        en                13
30                      text-exercise-group        en               169
31   input-expression-equal-match-challenge        en                 2
32                    grouped-text-exercise        en               601
33                                   applet        es                33
34                            text-solution        es               235
35                                   course        es                59
36                              math-puzzle        es                 3
37                              course-page        es               377
38                            text-exercise        es                28
39                                    video        es                50
40                      text-exercise-group        es                69
41                    grouped-text-exercise        es               230
42                                  article        es               312
43                                  article        fr                22
44                              math-puzzle        fr                 2
45                                   course        fr                11
46                            text-exercise        fr                 2
47                              course-page        fr               100
48                                  article        hi                 1
49   input-expression-equal-match-challenge        ta                 1
50                    grouped-text-exercise        ta               115
51               single-choice-right-answer        ta                 4
52                      text-exercise-group        ta                69
53                            text-exercise        ta                59
54                            text-solution        ta                43
55                                  article        ta                77
56                                    video        ta                 1
57                                   course        ta                 7
58             multiple-choice-wrong-answer        ta                 2
59                                   applet        ta                 4
60               single-choice-wrong-answer        ta                 6